name: CI
on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils

      - uses: actions/checkout@v2

      - name: Build image
        run: |
          set -x
          baseFileName="alpine-virthardened-$(date +%Y-%m-%d)"
          vhdDisk="$baseFileName.vhd"
          rawDisk="$baseFileName.raw"
          sudo ./alpine-make-vm-image \
              --image-format vpc \
              --image-subformat fixed \
              --image-size 512M \
              --repositories-file example/repositories \
              --packages "$(cat example/packages)" \
              --script-chroot \
              $vhdDisk -- ./example/configure.sh
          
          # Resize VHD to make it compatable with Azure    
          # https://docs.microsoft.com/en-us/azure/virtual-machines/linux/create-upload-generic#resizing-vhds    
          # Convert to RAW disk    
          qemu-img convert -f vpc -O raw $vhdDisk $rawDisk
          
          # Calculate the required size of the disk image so that the virtual size is aligned to 1 MB. 
          MB=$((1024*1024))
          size=$(qemu-img info -f raw --output json "$rawDisk" | gawk 'match($0, /"virtual-size": ([0-9]+),/, val) {print val[1]}')
          rounded_size=$(((($size+$MB-1)/$MB)*$MB))
          echo "Rounded Size = $rounded_size"
          
          # Resize the raw disk
          qemu-img resize $rawDisk $rounded_size
          
          # Convert the RAW disk back to a fixed-size VHD
          sudo qemu-img convert -f raw -o subformat=fixed,force_size -O vpc $rawDisk $vhdDisk
      
      - name: Upload Image
        uses: actions/upload-artifact@v2.3.1
        with:
          # Artifact name
          name: 'VHD'
          # A file, directory or wildcard pattern that describes what to upload
          path: '*.vhd'
          # The desired behavior if no files are found using the provided path.

